const DEFAULT_RASA_NLU_TRAINING_DATA_PATH = `${process.env.HUBOT_ENTERPRISE_ROOT}/training_data`;
const DEFAULT_CONFIDENCE = 0.6;

module.exports = {
  DEFAULT_RASA_NLU_TRAINING_DATA_PATH,
  DEFAULT_CONFIDENCE
};
